// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0
// 	protoc        v3.14.0
// source: group-service-api.proto

package group_service_api

import (
	context "context"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

type GetGroup_Request struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	GroupUuid string `protobuf:"bytes,1,opt,name=group_uuid,json=groupUuid,proto3" json:"group_uuid,omitempty"`
	GroupName string `protobuf:"bytes,2,opt,name=group_name,json=groupName,proto3" json:"group_name,omitempty"`
}

func (x *GetGroup_Request) Reset() {
	*x = GetGroup_Request{}
	if protoimpl.UnsafeEnabled {
		mi := &file_group_service_api_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetGroup_Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetGroup_Request) ProtoMessage() {}

func (x *GetGroup_Request) ProtoReflect() protoreflect.Message {
	mi := &file_group_service_api_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetGroup_Request.ProtoReflect.Descriptor instead.
func (*GetGroup_Request) Descriptor() ([]byte, []int) {
	return file_group_service_api_proto_rawDescGZIP(), []int{0}
}

func (x *GetGroup_Request) GetGroupUuid() string {
	if x != nil {
		return x.GroupUuid
	}
	return ""
}

func (x *GetGroup_Request) GetGroupName() string {
	if x != nil {
		return x.GroupName
	}
	return ""
}

type GetGroup_Response struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	GroupUuid            string `protobuf:"bytes,1,opt,name=group_uuid,json=groupUuid,proto3" json:"group_uuid,omitempty"`
	GroupName            string `protobuf:"bytes,2,opt,name=group_name,json=groupName,proto3" json:"group_name,omitempty"`
	SemesterStartAt      string `protobuf:"bytes,3,opt,name=semester_start_at,json=semesterStartAt,proto3" json:"semester_start_at,omitempty"`
	SemesterEndAt        string `protobuf:"bytes,4,opt,name=semester_end_at,json=semesterEndAt,proto3" json:"semester_end_at,omitempty"`
	IsFirstWeekNumerator bool   `protobuf:"varint,5,opt,name=is_first_week_numerator,json=isFirstWeekNumerator,proto3" json:"is_first_week_numerator,omitempty"`
	Department           string `protobuf:"bytes,6,opt,name=department,proto3" json:"department,omitempty"`
	Faculty              string `protobuf:"bytes,7,opt,name=faculty,proto3" json:"faculty,omitempty"`
}

func (x *GetGroup_Response) Reset() {
	*x = GetGroup_Response{}
	if protoimpl.UnsafeEnabled {
		mi := &file_group_service_api_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetGroup_Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetGroup_Response) ProtoMessage() {}

func (x *GetGroup_Response) ProtoReflect() protoreflect.Message {
	mi := &file_group_service_api_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetGroup_Response.ProtoReflect.Descriptor instead.
func (*GetGroup_Response) Descriptor() ([]byte, []int) {
	return file_group_service_api_proto_rawDescGZIP(), []int{1}
}

func (x *GetGroup_Response) GetGroupUuid() string {
	if x != nil {
		return x.GroupUuid
	}
	return ""
}

func (x *GetGroup_Response) GetGroupName() string {
	if x != nil {
		return x.GroupName
	}
	return ""
}

func (x *GetGroup_Response) GetSemesterStartAt() string {
	if x != nil {
		return x.SemesterStartAt
	}
	return ""
}

func (x *GetGroup_Response) GetSemesterEndAt() string {
	if x != nil {
		return x.SemesterEndAt
	}
	return ""
}

func (x *GetGroup_Response) GetIsFirstWeekNumerator() bool {
	if x != nil {
		return x.IsFirstWeekNumerator
	}
	return false
}

func (x *GetGroup_Response) GetDepartment() string {
	if x != nil {
		return x.Department
	}
	return ""
}

func (x *GetGroup_Response) GetFaculty() string {
	if x != nil {
		return x.Faculty
	}
	return ""
}

type AddGroups_Request struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	GroupsList []*AddGroups_GroupItem `protobuf:"bytes,1,rep,name=groups_list,json=groupsList,proto3" json:"groups_list,omitempty"`
}

func (x *AddGroups_Request) Reset() {
	*x = AddGroups_Request{}
	if protoimpl.UnsafeEnabled {
		mi := &file_group_service_api_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AddGroups_Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddGroups_Request) ProtoMessage() {}

func (x *AddGroups_Request) ProtoReflect() protoreflect.Message {
	mi := &file_group_service_api_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddGroups_Request.ProtoReflect.Descriptor instead.
func (*AddGroups_Request) Descriptor() ([]byte, []int) {
	return file_group_service_api_proto_rawDescGZIP(), []int{2}
}

func (x *AddGroups_Request) GetGroupsList() []*AddGroups_GroupItem {
	if x != nil {
		return x.GroupsList
	}
	return nil
}

type AddGroups_Response struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ResultsList []*AddGroups_ResultItem `protobuf:"bytes,2,rep,name=results_list,json=resultsList,proto3" json:"results_list,omitempty"`
}

func (x *AddGroups_Response) Reset() {
	*x = AddGroups_Response{}
	if protoimpl.UnsafeEnabled {
		mi := &file_group_service_api_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AddGroups_Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddGroups_Response) ProtoMessage() {}

func (x *AddGroups_Response) ProtoReflect() protoreflect.Message {
	mi := &file_group_service_api_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddGroups_Response.ProtoReflect.Descriptor instead.
func (*AddGroups_Response) Descriptor() ([]byte, []int) {
	return file_group_service_api_proto_rawDescGZIP(), []int{3}
}

func (x *AddGroups_Response) GetResultsList() []*AddGroups_ResultItem {
	if x != nil {
		return x.ResultsList
	}
	return nil
}

type AddGroups_GroupItem struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	GroupName            string `protobuf:"bytes,2,opt,name=group_name,json=groupName,proto3" json:"group_name,omitempty"`
	SemesterStartAt      string `protobuf:"bytes,3,opt,name=semester_start_at,json=semesterStartAt,proto3" json:"semester_start_at,omitempty"`
	SemesterEndAt        string `protobuf:"bytes,4,opt,name=semester_end_at,json=semesterEndAt,proto3" json:"semester_end_at,omitempty"`
	IsFirstWeekNumerator bool   `protobuf:"varint,5,opt,name=is_first_week_numerator,json=isFirstWeekNumerator,proto3" json:"is_first_week_numerator,omitempty"`
	Department           string `protobuf:"bytes,6,opt,name=department,proto3" json:"department,omitempty"`
	Faculty              string `protobuf:"bytes,7,opt,name=faculty,proto3" json:"faculty,omitempty"`
}

func (x *AddGroups_GroupItem) Reset() {
	*x = AddGroups_GroupItem{}
	if protoimpl.UnsafeEnabled {
		mi := &file_group_service_api_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AddGroups_GroupItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddGroups_GroupItem) ProtoMessage() {}

func (x *AddGroups_GroupItem) ProtoReflect() protoreflect.Message {
	mi := &file_group_service_api_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddGroups_GroupItem.ProtoReflect.Descriptor instead.
func (*AddGroups_GroupItem) Descriptor() ([]byte, []int) {
	return file_group_service_api_proto_rawDescGZIP(), []int{4}
}

func (x *AddGroups_GroupItem) GetGroupName() string {
	if x != nil {
		return x.GroupName
	}
	return ""
}

func (x *AddGroups_GroupItem) GetSemesterStartAt() string {
	if x != nil {
		return x.SemesterStartAt
	}
	return ""
}

func (x *AddGroups_GroupItem) GetSemesterEndAt() string {
	if x != nil {
		return x.SemesterEndAt
	}
	return ""
}

func (x *AddGroups_GroupItem) GetIsFirstWeekNumerator() bool {
	if x != nil {
		return x.IsFirstWeekNumerator
	}
	return false
}

func (x *AddGroups_GroupItem) GetDepartment() string {
	if x != nil {
		return x.Department
	}
	return ""
}

func (x *AddGroups_GroupItem) GetFaculty() string {
	if x != nil {
		return x.Faculty
	}
	return ""
}

type AddGroups_ResultItem struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Result bool   `protobuf:"varint,1,opt,name=result,proto3" json:"result,omitempty"`
	Error  string `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	Uuid   string `protobuf:"bytes,3,opt,name=uuid,proto3" json:"uuid,omitempty"`
}

func (x *AddGroups_ResultItem) Reset() {
	*x = AddGroups_ResultItem{}
	if protoimpl.UnsafeEnabled {
		mi := &file_group_service_api_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AddGroups_ResultItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddGroups_ResultItem) ProtoMessage() {}

func (x *AddGroups_ResultItem) ProtoReflect() protoreflect.Message {
	mi := &file_group_service_api_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddGroups_ResultItem.ProtoReflect.Descriptor instead.
func (*AddGroups_ResultItem) Descriptor() ([]byte, []int) {
	return file_group_service_api_proto_rawDescGZIP(), []int{5}
}

func (x *AddGroups_ResultItem) GetResult() bool {
	if x != nil {
		return x.Result
	}
	return false
}

func (x *AddGroups_ResultItem) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *AddGroups_ResultItem) GetUuid() string {
	if x != nil {
		return x.Uuid
	}
	return ""
}

type GetGroupList_Request struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Department string `protobuf:"bytes,1,opt,name=department,proto3" json:"department,omitempty"`
	Faculty    string `protobuf:"bytes,2,opt,name=faculty,proto3" json:"faculty,omitempty"`
}

func (x *GetGroupList_Request) Reset() {
	*x = GetGroupList_Request{}
	if protoimpl.UnsafeEnabled {
		mi := &file_group_service_api_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetGroupList_Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetGroupList_Request) ProtoMessage() {}

func (x *GetGroupList_Request) ProtoReflect() protoreflect.Message {
	mi := &file_group_service_api_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetGroupList_Request.ProtoReflect.Descriptor instead.
func (*GetGroupList_Request) Descriptor() ([]byte, []int) {
	return file_group_service_api_proto_rawDescGZIP(), []int{6}
}

func (x *GetGroupList_Request) GetDepartment() string {
	if x != nil {
		return x.Department
	}
	return ""
}

func (x *GetGroupList_Request) GetFaculty() string {
	if x != nil {
		return x.Faculty
	}
	return ""
}

type GetGroupList_Response struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	GroupsList []*GetGroupList_GroupItem `protobuf:"bytes,1,rep,name=groups_list,json=groupsList,proto3" json:"groups_list,omitempty"`
}

func (x *GetGroupList_Response) Reset() {
	*x = GetGroupList_Response{}
	if protoimpl.UnsafeEnabled {
		mi := &file_group_service_api_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetGroupList_Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetGroupList_Response) ProtoMessage() {}

func (x *GetGroupList_Response) ProtoReflect() protoreflect.Message {
	mi := &file_group_service_api_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetGroupList_Response.ProtoReflect.Descriptor instead.
func (*GetGroupList_Response) Descriptor() ([]byte, []int) {
	return file_group_service_api_proto_rawDescGZIP(), []int{7}
}

func (x *GetGroupList_Response) GetGroupsList() []*GetGroupList_GroupItem {
	if x != nil {
		return x.GroupsList
	}
	return nil
}

type GetGroupList_GroupItem struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	GroupUuid            string `protobuf:"bytes,1,opt,name=group_uuid,json=groupUuid,proto3" json:"group_uuid,omitempty"`
	GroupName            string `protobuf:"bytes,2,opt,name=group_name,json=groupName,proto3" json:"group_name,omitempty"`
	SemesterStartAt      string `protobuf:"bytes,3,opt,name=semester_start_at,json=semesterStartAt,proto3" json:"semester_start_at,omitempty"`
	SemesterEndAt        string `protobuf:"bytes,4,opt,name=semester_end_at,json=semesterEndAt,proto3" json:"semester_end_at,omitempty"`
	IsFirstWeekNumerator bool   `protobuf:"varint,5,opt,name=is_first_week_numerator,json=isFirstWeekNumerator,proto3" json:"is_first_week_numerator,omitempty"`
	Department           string `protobuf:"bytes,6,opt,name=department,proto3" json:"department,omitempty"`
	Faculty              string `protobuf:"bytes,7,opt,name=faculty,proto3" json:"faculty,omitempty"`
}

func (x *GetGroupList_GroupItem) Reset() {
	*x = GetGroupList_GroupItem{}
	if protoimpl.UnsafeEnabled {
		mi := &file_group_service_api_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetGroupList_GroupItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetGroupList_GroupItem) ProtoMessage() {}

func (x *GetGroupList_GroupItem) ProtoReflect() protoreflect.Message {
	mi := &file_group_service_api_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetGroupList_GroupItem.ProtoReflect.Descriptor instead.
func (*GetGroupList_GroupItem) Descriptor() ([]byte, []int) {
	return file_group_service_api_proto_rawDescGZIP(), []int{8}
}

func (x *GetGroupList_GroupItem) GetGroupUuid() string {
	if x != nil {
		return x.GroupUuid
	}
	return ""
}

func (x *GetGroupList_GroupItem) GetGroupName() string {
	if x != nil {
		return x.GroupName
	}
	return ""
}

func (x *GetGroupList_GroupItem) GetSemesterStartAt() string {
	if x != nil {
		return x.SemesterStartAt
	}
	return ""
}

func (x *GetGroupList_GroupItem) GetSemesterEndAt() string {
	if x != nil {
		return x.SemesterEndAt
	}
	return ""
}

func (x *GetGroupList_GroupItem) GetIsFirstWeekNumerator() bool {
	if x != nil {
		return x.IsFirstWeekNumerator
	}
	return false
}

func (x *GetGroupList_GroupItem) GetDepartment() string {
	if x != nil {
		return x.Department
	}
	return ""
}

func (x *GetGroupList_GroupItem) GetFaculty() string {
	if x != nil {
		return x.Faculty
	}
	return ""
}

var File_group_service_api_proto protoreflect.FileDescriptor

var file_group_service_api_proto_rawDesc = []byte{
	0x0a, 0x17, 0x67, 0x72, 0x6f, 0x75, 0x70, 0x2d, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2d,
	0x61, 0x70, 0x69, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x11, 0x67, 0x72, 0x6f, 0x75, 0x70,
	0x5f, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x5f, 0x61, 0x70, 0x69, 0x22, 0x50, 0x0a, 0x10,
	0x47, 0x65, 0x74, 0x47, 0x72, 0x6f, 0x75, 0x70, 0x5f, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x12, 0x1d, 0x0a, 0x0a, 0x67, 0x72, 0x6f, 0x75, 0x70, 0x5f, 0x75, 0x75, 0x69, 0x64, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x67, 0x72, 0x6f, 0x75, 0x70, 0x55, 0x75, 0x69, 0x64, 0x12,
	0x1d, 0x0a, 0x0a, 0x67, 0x72, 0x6f, 0x75, 0x70, 0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x09, 0x67, 0x72, 0x6f, 0x75, 0x70, 0x4e, 0x61, 0x6d, 0x65, 0x22, 0x96,
	0x02, 0x0a, 0x11, 0x47, 0x65, 0x74, 0x47, 0x72, 0x6f, 0x75, 0x70, 0x5f, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x12, 0x1d, 0x0a, 0x0a, 0x67, 0x72, 0x6f, 0x75, 0x70, 0x5f, 0x75, 0x75,
	0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x67, 0x72, 0x6f, 0x75, 0x70, 0x55,
	0x75, 0x69, 0x64, 0x12, 0x1d, 0x0a, 0x0a, 0x67, 0x72, 0x6f, 0x75, 0x70, 0x5f, 0x6e, 0x61, 0x6d,
	0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x67, 0x72, 0x6f, 0x75, 0x70, 0x4e, 0x61,
	0x6d, 0x65, 0x12, 0x2a, 0x0a, 0x11, 0x73, 0x65, 0x6d, 0x65, 0x73, 0x74, 0x65, 0x72, 0x5f, 0x73,
	0x74, 0x61, 0x72, 0x74, 0x5f, 0x61, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0f, 0x73,
	0x65, 0x6d, 0x65, 0x73, 0x74, 0x65, 0x72, 0x53, 0x74, 0x61, 0x72, 0x74, 0x41, 0x74, 0x12, 0x26,
	0x0a, 0x0f, 0x73, 0x65, 0x6d, 0x65, 0x73, 0x74, 0x65, 0x72, 0x5f, 0x65, 0x6e, 0x64, 0x5f, 0x61,
	0x74, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0d, 0x73, 0x65, 0x6d, 0x65, 0x73, 0x74, 0x65,
	0x72, 0x45, 0x6e, 0x64, 0x41, 0x74, 0x12, 0x35, 0x0a, 0x17, 0x69, 0x73, 0x5f, 0x66, 0x69, 0x72,
	0x73, 0x74, 0x5f, 0x77, 0x65, 0x65, 0x6b, 0x5f, 0x6e, 0x75, 0x6d, 0x65, 0x72, 0x61, 0x74, 0x6f,
	0x72, 0x18, 0x05, 0x20, 0x01, 0x28, 0x08, 0x52, 0x14, 0x69, 0x73, 0x46, 0x69, 0x72, 0x73, 0x74,
	0x57, 0x65, 0x65, 0x6b, 0x4e, 0x75, 0x6d, 0x65, 0x72, 0x61, 0x74, 0x6f, 0x72, 0x12, 0x1e, 0x0a,
	0x0a, 0x64, 0x65, 0x70, 0x61, 0x72, 0x74, 0x6d, 0x65, 0x6e, 0x74, 0x18, 0x06, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x0a, 0x64, 0x65, 0x70, 0x61, 0x72, 0x74, 0x6d, 0x65, 0x6e, 0x74, 0x12, 0x18, 0x0a,
	0x07, 0x66, 0x61, 0x63, 0x75, 0x6c, 0x74, 0x79, 0x18, 0x07, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07,
	0x66, 0x61, 0x63, 0x75, 0x6c, 0x74, 0x79, 0x22, 0x5c, 0x0a, 0x11, 0x41, 0x64, 0x64, 0x47, 0x72,
	0x6f, 0x75, 0x70, 0x73, 0x5f, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x47, 0x0a, 0x0b,
	0x67, 0x72, 0x6f, 0x75, 0x70, 0x73, 0x5f, 0x6c, 0x69, 0x73, 0x74, 0x18, 0x01, 0x20, 0x03, 0x28,
	0x0b, 0x32, 0x26, 0x2e, 0x67, 0x72, 0x6f, 0x75, 0x70, 0x5f, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63,
	0x65, 0x5f, 0x61, 0x70, 0x69, 0x2e, 0x41, 0x64, 0x64, 0x47, 0x72, 0x6f, 0x75, 0x70, 0x73, 0x5f,
	0x47, 0x72, 0x6f, 0x75, 0x70, 0x49, 0x74, 0x65, 0x6d, 0x52, 0x0a, 0x67, 0x72, 0x6f, 0x75, 0x70,
	0x73, 0x4c, 0x69, 0x73, 0x74, 0x22, 0x60, 0x0a, 0x12, 0x41, 0x64, 0x64, 0x47, 0x72, 0x6f, 0x75,
	0x70, 0x73, 0x5f, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x4a, 0x0a, 0x0c, 0x72,
	0x65, 0x73, 0x75, 0x6c, 0x74, 0x73, 0x5f, 0x6c, 0x69, 0x73, 0x74, 0x18, 0x02, 0x20, 0x03, 0x28,
	0x0b, 0x32, 0x27, 0x2e, 0x67, 0x72, 0x6f, 0x75, 0x70, 0x5f, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63,
	0x65, 0x5f, 0x61, 0x70, 0x69, 0x2e, 0x41, 0x64, 0x64, 0x47, 0x72, 0x6f, 0x75, 0x70, 0x73, 0x5f,
	0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x49, 0x74, 0x65, 0x6d, 0x52, 0x0b, 0x72, 0x65, 0x73, 0x75,
	0x6c, 0x74, 0x73, 0x4c, 0x69, 0x73, 0x74, 0x22, 0xf9, 0x01, 0x0a, 0x13, 0x41, 0x64, 0x64, 0x47,
	0x72, 0x6f, 0x75, 0x70, 0x73, 0x5f, 0x47, 0x72, 0x6f, 0x75, 0x70, 0x49, 0x74, 0x65, 0x6d, 0x12,
	0x1d, 0x0a, 0x0a, 0x67, 0x72, 0x6f, 0x75, 0x70, 0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x09, 0x67, 0x72, 0x6f, 0x75, 0x70, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x2a,
	0x0a, 0x11, 0x73, 0x65, 0x6d, 0x65, 0x73, 0x74, 0x65, 0x72, 0x5f, 0x73, 0x74, 0x61, 0x72, 0x74,
	0x5f, 0x61, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0f, 0x73, 0x65, 0x6d, 0x65, 0x73,
	0x74, 0x65, 0x72, 0x53, 0x74, 0x61, 0x72, 0x74, 0x41, 0x74, 0x12, 0x26, 0x0a, 0x0f, 0x73, 0x65,
	0x6d, 0x65, 0x73, 0x74, 0x65, 0x72, 0x5f, 0x65, 0x6e, 0x64, 0x5f, 0x61, 0x74, 0x18, 0x04, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x0d, 0x73, 0x65, 0x6d, 0x65, 0x73, 0x74, 0x65, 0x72, 0x45, 0x6e, 0x64,
	0x41, 0x74, 0x12, 0x35, 0x0a, 0x17, 0x69, 0x73, 0x5f, 0x66, 0x69, 0x72, 0x73, 0x74, 0x5f, 0x77,
	0x65, 0x65, 0x6b, 0x5f, 0x6e, 0x75, 0x6d, 0x65, 0x72, 0x61, 0x74, 0x6f, 0x72, 0x18, 0x05, 0x20,
	0x01, 0x28, 0x08, 0x52, 0x14, 0x69, 0x73, 0x46, 0x69, 0x72, 0x73, 0x74, 0x57, 0x65, 0x65, 0x6b,
	0x4e, 0x75, 0x6d, 0x65, 0x72, 0x61, 0x74, 0x6f, 0x72, 0x12, 0x1e, 0x0a, 0x0a, 0x64, 0x65, 0x70,
	0x61, 0x72, 0x74, 0x6d, 0x65, 0x6e, 0x74, 0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x64,
	0x65, 0x70, 0x61, 0x72, 0x74, 0x6d, 0x65, 0x6e, 0x74, 0x12, 0x18, 0x0a, 0x07, 0x66, 0x61, 0x63,
	0x75, 0x6c, 0x74, 0x79, 0x18, 0x07, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x66, 0x61, 0x63, 0x75,
	0x6c, 0x74, 0x79, 0x22, 0x58, 0x0a, 0x14, 0x41, 0x64, 0x64, 0x47, 0x72, 0x6f, 0x75, 0x70, 0x73,
	0x5f, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x49, 0x74, 0x65, 0x6d, 0x12, 0x16, 0x0a, 0x06, 0x72,
	0x65, 0x73, 0x75, 0x6c, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x06, 0x72, 0x65, 0x73,
	0x75, 0x6c, 0x74, 0x12, 0x14, 0x0a, 0x05, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x05, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x12, 0x12, 0x0a, 0x04, 0x75, 0x75, 0x69,
	0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x75, 0x75, 0x69, 0x64, 0x22, 0x50, 0x0a,
	0x14, 0x47, 0x65, 0x74, 0x47, 0x72, 0x6f, 0x75, 0x70, 0x4c, 0x69, 0x73, 0x74, 0x5f, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1e, 0x0a, 0x0a, 0x64, 0x65, 0x70, 0x61, 0x72, 0x74, 0x6d,
	0x65, 0x6e, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x64, 0x65, 0x70, 0x61, 0x72,
	0x74, 0x6d, 0x65, 0x6e, 0x74, 0x12, 0x18, 0x0a, 0x07, 0x66, 0x61, 0x63, 0x75, 0x6c, 0x74, 0x79,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x66, 0x61, 0x63, 0x75, 0x6c, 0x74, 0x79, 0x22,
	0x63, 0x0a, 0x15, 0x47, 0x65, 0x74, 0x47, 0x72, 0x6f, 0x75, 0x70, 0x4c, 0x69, 0x73, 0x74, 0x5f,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x4a, 0x0a, 0x0b, 0x67, 0x72, 0x6f, 0x75,
	0x70, 0x73, 0x5f, 0x6c, 0x69, 0x73, 0x74, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x29, 0x2e,
	0x67, 0x72, 0x6f, 0x75, 0x70, 0x5f, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x5f, 0x61, 0x70,
	0x69, 0x2e, 0x47, 0x65, 0x74, 0x47, 0x72, 0x6f, 0x75, 0x70, 0x4c, 0x69, 0x73, 0x74, 0x5f, 0x47,
	0x72, 0x6f, 0x75, 0x70, 0x49, 0x74, 0x65, 0x6d, 0x52, 0x0a, 0x67, 0x72, 0x6f, 0x75, 0x70, 0x73,
	0x4c, 0x69, 0x73, 0x74, 0x22, 0x9b, 0x02, 0x0a, 0x16, 0x47, 0x65, 0x74, 0x47, 0x72, 0x6f, 0x75,
	0x70, 0x4c, 0x69, 0x73, 0x74, 0x5f, 0x47, 0x72, 0x6f, 0x75, 0x70, 0x49, 0x74, 0x65, 0x6d, 0x12,
	0x1d, 0x0a, 0x0a, 0x67, 0x72, 0x6f, 0x75, 0x70, 0x5f, 0x75, 0x75, 0x69, 0x64, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x09, 0x67, 0x72, 0x6f, 0x75, 0x70, 0x55, 0x75, 0x69, 0x64, 0x12, 0x1d,
	0x0a, 0x0a, 0x67, 0x72, 0x6f, 0x75, 0x70, 0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x09, 0x67, 0x72, 0x6f, 0x75, 0x70, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x2a, 0x0a,
	0x11, 0x73, 0x65, 0x6d, 0x65, 0x73, 0x74, 0x65, 0x72, 0x5f, 0x73, 0x74, 0x61, 0x72, 0x74, 0x5f,
	0x61, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0f, 0x73, 0x65, 0x6d, 0x65, 0x73, 0x74,
	0x65, 0x72, 0x53, 0x74, 0x61, 0x72, 0x74, 0x41, 0x74, 0x12, 0x26, 0x0a, 0x0f, 0x73, 0x65, 0x6d,
	0x65, 0x73, 0x74, 0x65, 0x72, 0x5f, 0x65, 0x6e, 0x64, 0x5f, 0x61, 0x74, 0x18, 0x04, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x0d, 0x73, 0x65, 0x6d, 0x65, 0x73, 0x74, 0x65, 0x72, 0x45, 0x6e, 0x64, 0x41,
	0x74, 0x12, 0x35, 0x0a, 0x17, 0x69, 0x73, 0x5f, 0x66, 0x69, 0x72, 0x73, 0x74, 0x5f, 0x77, 0x65,
	0x65, 0x6b, 0x5f, 0x6e, 0x75, 0x6d, 0x65, 0x72, 0x61, 0x74, 0x6f, 0x72, 0x18, 0x05, 0x20, 0x01,
	0x28, 0x08, 0x52, 0x14, 0x69, 0x73, 0x46, 0x69, 0x72, 0x73, 0x74, 0x57, 0x65, 0x65, 0x6b, 0x4e,
	0x75, 0x6d, 0x65, 0x72, 0x61, 0x74, 0x6f, 0x72, 0x12, 0x1e, 0x0a, 0x0a, 0x64, 0x65, 0x70, 0x61,
	0x72, 0x74, 0x6d, 0x65, 0x6e, 0x74, 0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x64, 0x65,
	0x70, 0x61, 0x72, 0x74, 0x6d, 0x65, 0x6e, 0x74, 0x12, 0x18, 0x0a, 0x07, 0x66, 0x61, 0x63, 0x75,
	0x6c, 0x74, 0x79, 0x18, 0x07, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x66, 0x61, 0x63, 0x75, 0x6c,
	0x74, 0x79, 0x32, 0xa2, 0x02, 0x0a, 0x0c, 0x47, 0x72, 0x6f, 0x75, 0x70, 0x53, 0x65, 0x72, 0x76,
	0x69, 0x63, 0x65, 0x12, 0x55, 0x0a, 0x08, 0x47, 0x65, 0x74, 0x47, 0x72, 0x6f, 0x75, 0x70, 0x12,
	0x23, 0x2e, 0x67, 0x72, 0x6f, 0x75, 0x70, 0x5f, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x5f,
	0x61, 0x70, 0x69, 0x2e, 0x47, 0x65, 0x74, 0x47, 0x72, 0x6f, 0x75, 0x70, 0x5f, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x1a, 0x24, 0x2e, 0x67, 0x72, 0x6f, 0x75, 0x70, 0x5f, 0x73, 0x65, 0x72,
	0x76, 0x69, 0x63, 0x65, 0x5f, 0x61, 0x70, 0x69, 0x2e, 0x47, 0x65, 0x74, 0x47, 0x72, 0x6f, 0x75,
	0x70, 0x5f, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x58, 0x0a, 0x09, 0x41, 0x64,
	0x64, 0x47, 0x72, 0x6f, 0x75, 0x70, 0x73, 0x12, 0x24, 0x2e, 0x67, 0x72, 0x6f, 0x75, 0x70, 0x5f,
	0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x5f, 0x61, 0x70, 0x69, 0x2e, 0x41, 0x64, 0x64, 0x47,
	0x72, 0x6f, 0x75, 0x70, 0x73, 0x5f, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x25, 0x2e,
	0x67, 0x72, 0x6f, 0x75, 0x70, 0x5f, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x5f, 0x61, 0x70,
	0x69, 0x2e, 0x41, 0x64, 0x64, 0x47, 0x72, 0x6f, 0x75, 0x70, 0x73, 0x5f, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x12, 0x61, 0x0a, 0x0c, 0x47, 0x65, 0x74, 0x47, 0x72, 0x6f, 0x75, 0x70,
	0x4c, 0x69, 0x73, 0x74, 0x12, 0x27, 0x2e, 0x67, 0x72, 0x6f, 0x75, 0x70, 0x5f, 0x73, 0x65, 0x72,
	0x76, 0x69, 0x63, 0x65, 0x5f, 0x61, 0x70, 0x69, 0x2e, 0x47, 0x65, 0x74, 0x47, 0x72, 0x6f, 0x75,
	0x70, 0x4c, 0x69, 0x73, 0x74, 0x5f, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x28, 0x2e,
	0x67, 0x72, 0x6f, 0x75, 0x70, 0x5f, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x5f, 0x61, 0x70,
	0x69, 0x2e, 0x47, 0x65, 0x74, 0x47, 0x72, 0x6f, 0x75, 0x70, 0x4c, 0x69, 0x73, 0x74, 0x5f, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x42, 0x15, 0x5a, 0x13, 0x2e, 0x3b, 0x67, 0x72, 0x6f,
	0x75, 0x70, 0x5f, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x5f, 0x61, 0x70, 0x69, 0x62, 0x06,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_group_service_api_proto_rawDescOnce sync.Once
	file_group_service_api_proto_rawDescData = file_group_service_api_proto_rawDesc
)

func file_group_service_api_proto_rawDescGZIP() []byte {
	file_group_service_api_proto_rawDescOnce.Do(func() {
		file_group_service_api_proto_rawDescData = protoimpl.X.CompressGZIP(file_group_service_api_proto_rawDescData)
	})
	return file_group_service_api_proto_rawDescData
}

var file_group_service_api_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_group_service_api_proto_goTypes = []interface{}{
	(*GetGroup_Request)(nil),       // 0: group_service_api.GetGroup_Request
	(*GetGroup_Response)(nil),      // 1: group_service_api.GetGroup_Response
	(*AddGroups_Request)(nil),      // 2: group_service_api.AddGroups_Request
	(*AddGroups_Response)(nil),     // 3: group_service_api.AddGroups_Response
	(*AddGroups_GroupItem)(nil),    // 4: group_service_api.AddGroups_GroupItem
	(*AddGroups_ResultItem)(nil),   // 5: group_service_api.AddGroups_ResultItem
	(*GetGroupList_Request)(nil),   // 6: group_service_api.GetGroupList_Request
	(*GetGroupList_Response)(nil),  // 7: group_service_api.GetGroupList_Response
	(*GetGroupList_GroupItem)(nil), // 8: group_service_api.GetGroupList_GroupItem
}
var file_group_service_api_proto_depIdxs = []int32{
	4, // 0: group_service_api.AddGroups_Request.groups_list:type_name -> group_service_api.AddGroups_GroupItem
	5, // 1: group_service_api.AddGroups_Response.results_list:type_name -> group_service_api.AddGroups_ResultItem
	8, // 2: group_service_api.GetGroupList_Response.groups_list:type_name -> group_service_api.GetGroupList_GroupItem
	0, // 3: group_service_api.GroupService.GetGroup:input_type -> group_service_api.GetGroup_Request
	2, // 4: group_service_api.GroupService.AddGroups:input_type -> group_service_api.AddGroups_Request
	6, // 5: group_service_api.GroupService.GetGroupList:input_type -> group_service_api.GetGroupList_Request
	1, // 6: group_service_api.GroupService.GetGroup:output_type -> group_service_api.GetGroup_Response
	3, // 7: group_service_api.GroupService.AddGroups:output_type -> group_service_api.AddGroups_Response
	7, // 8: group_service_api.GroupService.GetGroupList:output_type -> group_service_api.GetGroupList_Response
	6, // [6:9] is the sub-list for method output_type
	3, // [3:6] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_group_service_api_proto_init() }
func file_group_service_api_proto_init() {
	if File_group_service_api_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_group_service_api_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetGroup_Request); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_group_service_api_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetGroup_Response); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_group_service_api_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AddGroups_Request); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_group_service_api_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AddGroups_Response); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_group_service_api_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AddGroups_GroupItem); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_group_service_api_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AddGroups_ResultItem); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_group_service_api_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetGroupList_Request); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_group_service_api_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetGroupList_Response); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_group_service_api_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetGroupList_GroupItem); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_group_service_api_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_group_service_api_proto_goTypes,
		DependencyIndexes: file_group_service_api_proto_depIdxs,
		MessageInfos:      file_group_service_api_proto_msgTypes,
	}.Build()
	File_group_service_api_proto = out.File
	file_group_service_api_proto_rawDesc = nil
	file_group_service_api_proto_goTypes = nil
	file_group_service_api_proto_depIdxs = nil
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// GroupServiceClient is the client API for GroupService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type GroupServiceClient interface {
	// возвращает указанную группу
	GetGroup(ctx context.Context, in *GetGroup_Request, opts ...grpc.CallOption) (*GetGroup_Response, error)
	// добавляет новую группу
	AddGroups(ctx context.Context, in *AddGroups_Request, opts ...grpc.CallOption) (*AddGroups_Response, error)
	// возвращает список групп
	GetGroupList(ctx context.Context, in *GetGroupList_Request, opts ...grpc.CallOption) (*GetGroupList_Response, error)
}

type groupServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewGroupServiceClient(cc grpc.ClientConnInterface) GroupServiceClient {
	return &groupServiceClient{cc}
}

func (c *groupServiceClient) GetGroup(ctx context.Context, in *GetGroup_Request, opts ...grpc.CallOption) (*GetGroup_Response, error) {
	out := new(GetGroup_Response)
	err := c.cc.Invoke(ctx, "/group_service_api.GroupService/GetGroup", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *groupServiceClient) AddGroups(ctx context.Context, in *AddGroups_Request, opts ...grpc.CallOption) (*AddGroups_Response, error) {
	out := new(AddGroups_Response)
	err := c.cc.Invoke(ctx, "/group_service_api.GroupService/AddGroups", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *groupServiceClient) GetGroupList(ctx context.Context, in *GetGroupList_Request, opts ...grpc.CallOption) (*GetGroupList_Response, error) {
	out := new(GetGroupList_Response)
	err := c.cc.Invoke(ctx, "/group_service_api.GroupService/GetGroupList", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// GroupServiceServer is the server API for GroupService service.
type GroupServiceServer interface {
	// возвращает указанную группу
	GetGroup(context.Context, *GetGroup_Request) (*GetGroup_Response, error)
	// добавляет новую группу
	AddGroups(context.Context, *AddGroups_Request) (*AddGroups_Response, error)
	// возвращает список групп
	GetGroupList(context.Context, *GetGroupList_Request) (*GetGroupList_Response, error)
}

// UnimplementedGroupServiceServer can be embedded to have forward compatible implementations.
type UnimplementedGroupServiceServer struct {
}

func (*UnimplementedGroupServiceServer) GetGroup(context.Context, *GetGroup_Request) (*GetGroup_Response, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetGroup not implemented")
}
func (*UnimplementedGroupServiceServer) AddGroups(context.Context, *AddGroups_Request) (*AddGroups_Response, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AddGroups not implemented")
}
func (*UnimplementedGroupServiceServer) GetGroupList(context.Context, *GetGroupList_Request) (*GetGroupList_Response, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetGroupList not implemented")
}

func RegisterGroupServiceServer(s *grpc.Server, srv GroupServiceServer) {
	s.RegisterService(&_GroupService_serviceDesc, srv)
}

func _GroupService_GetGroup_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetGroup_Request)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GroupServiceServer).GetGroup(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/group_service_api.GroupService/GetGroup",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GroupServiceServer).GetGroup(ctx, req.(*GetGroup_Request))
	}
	return interceptor(ctx, in, info, handler)
}

func _GroupService_AddGroups_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddGroups_Request)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GroupServiceServer).AddGroups(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/group_service_api.GroupService/AddGroups",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GroupServiceServer).AddGroups(ctx, req.(*AddGroups_Request))
	}
	return interceptor(ctx, in, info, handler)
}

func _GroupService_GetGroupList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetGroupList_Request)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GroupServiceServer).GetGroupList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/group_service_api.GroupService/GetGroupList",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GroupServiceServer).GetGroupList(ctx, req.(*GetGroupList_Request))
	}
	return interceptor(ctx, in, info, handler)
}

var _GroupService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "group_service_api.GroupService",
	HandlerType: (*GroupServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetGroup",
			Handler:    _GroupService_GetGroup_Handler,
		},
		{
			MethodName: "AddGroups",
			Handler:    _GroupService_AddGroups_Handler,
		},
		{
			MethodName: "GetGroupList",
			Handler:    _GroupService_GetGroupList_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "group-service-api.proto",
}
